sudo: false
language: ruby
rvm:
  - 2.1.3
before_script:
  - export RAILS_ENV=test
  - cp .example-env .env
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install imagemagick -y
